server:
  port: 8080

spring:
  jpa:
    database: default
    hibernate:
      ddl-auto: validate
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
properties:
  beekeeper:
    default-cleanup-delay: P3D
    default-expired-cleanup-delay: P356D
  apiary:
    cleanup-delay-property-key: beekeeper.unreferenced.data.retention.period
    expired-cleanup-delay-property-key: beekeeper.expired.data.retention.period